<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
    <PackageReference Include="ThermoFisher.CommonCore.RawFileReader" Version="8.0.37" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MassSpectrometry\MassSpectrometry.csproj" />
    <ProjectReference Include="..\MzLibUtil\MzLibUtil.csproj" />
    <ProjectReference Include="..\Readers\Readers.csproj" />
    <ProjectReference Include="..\UsefulProteomicsDatabases\UsefulProteomicsDatabases.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Test</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
  <ItemGroup>
    <None Update="Bruker\baf2sql_c.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Bruker\baf2sql_c.lib">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Bruker\msvcp110.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Bruker\msvcr110.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Bruker\vcomp110.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="timsdata.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="timsdata.lib">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="timsTOF\baf2sql_c.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="timsTOF\baf2sql_c.lib">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
